<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\DeviceMonitoring.Windows\DeviceMonitoring.Windows.csproj" />
    <ProjectReference Include="..\..\..\..\modules\device-monitoring\src\DeviceMonitoring.Abstractions\DeviceMonitoring.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\..\modules\device-monitoring\src\DeviceMonitoring.Generic\DeviceMonitoring.Generic.csproj" />
    <ProjectReference Include="..\..\..\..\modules\hosting\src\Hosting.Windows\Hosting.Windows.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
